version: '3.8'

services:
  app:
    build:
      context: ./laravel-app
      dockerfile: Dockerfile
    container_name: mini-curso-laravel-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./laravel-app:/var/www
      - /var/www/vendor
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
    networks:
      - mini-curso-network

  db:
    image: postgres:15-alpine
    container_name: mini-curso-postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: laravel
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mini-curso-network

volumes:
  pgdata:
    driver: local

networks:
  mini-curso-network:
    driver: bridge
