apiVersion: v1
kind: Service
metadata:
  name: laravel-service
  labels:
    app: laravel
spec:
  type: NodePort
  selector:
    app: laravel
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
      protocol: TCP
